### ISSUE TITLE
[BUG] - 404 error when trying to open Live App

### ISSUE THREAD

**Issue by Meketh74** [Umbra-Aeterna-Labs/phasepharmer#60]
### Description of bug ###

getting a 404 page not found error with  https://umbra-aeterna-labs.github.io/phasepharmer

--------------------------------------------------------------------------------
### Expected behavior ###

--------------------------------------------------------------------------------
### Steps to reproduce the behavior ###

1. 
2. 
3. 

--------------------------------------------------------------------------------
### Name(s) of web browser(s) used ###

Firefox & Chrome (both latest version)

--------------------------------------------------------------------------------
### Version(s) of app ###

Latest live link: https://umbra-aeterna-labs.github.io/phasepharmer

--------------------------------------------------------------------------------
### Additional info ###

--------------------------------------------------------------------------------
<img width="1150" alt="404" src="https://user-images.githubusercontent.com/69805450/212498993-431aa36a-69b3-4b29-8a4f-8ad40009a282.PNG">

**Comment by chrismabon** [comment]
Enabled github-pages environment required to host the app. Apparently I forgot to do that when I restored the repository recently. Please let me know if you still cannot reach the app (clear browser cache for the site if needed).

Thank you for bringing this to my attention, @Meketh74.
