### ISSUE TITLE
[BUG] - Box timer Start date is calculated wrongly

### ISSUE THREAD

**Issue by Meketh74** [Umbra-Aeterna-Labs/phasepharmer#61]
### Description of bug ###

Bug: 
In the box timer, the start date is calculated wrongly (it is off by 1 month, shows right now Feb 19th as start date). Furthermore, the time modifications through e.g. practice boxes are not calculated into the timer (see picture)

Additional feature request: Would it be possible to calculate and add the actual end date and time besides showing a counter that is counting back. 

--------------------------------------------------------------------------------
### Expected behavior ###

--------------------------------------------------------------------------------
### Steps to reproduce the behavior ###

1. Within current live app
2. 
3. 

--------------------------------------------------------------------------------
### Name(s) of web browser(s) used ###

--------------------------------------------------------------------------------
### Version(s) of app ###

--------------------------------------------------------------------------------
### Additional info ###

--------------------------------------------------------------------------------
<img width="1108" alt="Boxtimers" src="https://user-images.githubusercontent.com/69805450/213565902-8dba7e8d-3349-43c5-992a-d52c29701bf9.PNG">

**Comment by chrismabon** [comment]
This fix will be implemented in the successor app to PhasePharmer, "[Tempus Lunae](https://github.com/Umbra-Aeterna-Labs/tempus-lunae)".
Just saving myself some unnecessary work by only fixing it once.
